/**
 * Discipline-specific landing page data.
 * Each entry powers one /custom-{discipline}-suit page.
 * Single source of truth — edit copy here to update all 6 pages.
 */

export const DISCIPLINE_DATA = {
  "drag-racing": {
    slug: "custom-drag-racing-suit",
    breadcrumb: "Custom Drag Racing Suit",
    disciplineTag: "Drag Racing",
    disciplineFullName: "Drag Racing",
    suitNoun: "drag racing suits",
    h1First: "Custom Drag",
    h1Second: "Racing Suits",
    subtitle: "SFI-certified custom drag racing suits for NHRA, IHRA, and bracket racing. Class-rated from SFI 3.2A/1 for sportsman classes to SFI 3.2A/15 for cars quicker than 9.99 ET. From $329.",
    primaryCtaHref: "/custom-race-suit/order",
    primaryCtaText: "Design Your Drag Suit",
    certBadge: "SFI Certified",
    builtForIntro: "Drag racing suits face a specific risk profile — short, high-fuel-load runs with potential nitromethane or alcohol exposure, plus the burnout box. Our custom drag racing suits are built around four design priorities:",
    builtForPoints: [
      { title: "Class-rated SFI certification", detail: "SFI 3.2A/1 for 10.00+ ET, 3.2A/5 for 9.99 ET and quicker, 3.2A/15 for sub-7.49 ET classes. Higher tiers available on request." },
      { title: "Lightweight construction for bracket racing", detail: "Single-layer Nomex® for classes that don't require multi-layer — keeps weight and heat down during long lanes-and-staging waits." },
      { title: "Reinforced shoulder and knee panels", detail: "For the inevitable race-day slides and tow strap interactions." },
      { title: "Sponsor-ready custom graphics", detail: "Sublimated graphics, embroidered driver name, team patches — Pro Stock-quality finish at sportsman price." },
    ],
    sanctioningIntro: "Drag racing has strict, well-defined SFI tier requirements by elapsed time. Our suits are built to current 2026 rulebook specifications:",
    sanctioningBodies: [
      { name: "NHRA Sportsman (10.00–13.99 ET)", requirement: "SFI 3.2A/1 jacket minimum required for sub-13.99 ET classes." },
      { name: "NHRA Pro Sportsman (7.50–9.99 ET)", requirement: "SFI 3.2A/5 multi-layer jacket and pants required. Head sock SFI 3.3 required." },
      { name: "NHRA Pro Stock and faster", requirement: "SFI 3.2A/15 minimum, full multi-layer construction with head and hand protection." },
      { name: "IHRA Sportsman and Pro", requirement: "Similar tier structure to NHRA — confirm against current IHRA Rulebook before each season." },
      { name: "Bracket racing / weekly tracks", requirement: "Track-specific rules; most weekly tracks accept SFI 3.2A/1 for cars 11.99 ET and slower." },
    ],
    sanctioningCallout: "Buy for the car you intend to build, not the car in the trailer today. Suits aren't rated by ET — they're rated by spec. If you build the car faster, your suit has to keep up.",
    relatedReading: [
      { href: "/blog/drag-racing-suit-requirements", title: "Drag Racing Suit Requirements — NHRA, IHRA Rules", note: "Definitive guide" },
      { href: "/blog/sfi-rated-racing-suit-by-class", title: "SFI Rated Racing Suit by Class", note: "Discipline-by-discipline rating breakdown" },
      { href: "/blog/tpp-rating-explained", title: "TPP Rating Explained", note: "Why two SFI 3.2A/5 suits can have different protection" },
    ],
    ctaTitle: "Ready to Design Your Custom Drag Racing Suit?",
    ctaSubtitle: "SFI 3.2A/1 single-layer to SFI 3.2A/15 multi-layer — built from genuine Nomex® meta-aramid. Custom-fit to your measurements. Starting at $329 with free shipping.",
  },

  "sprint-car": {
    slug: "custom-sprint-car-suit",
    breadcrumb: "Custom Sprint Car Suit",
    disciplineTag: "Sprint Car",
    disciplineFullName: "Sprint Car Racing",
    suitNoun: "sprint car suits",
    h1First: "Custom Sprint",
    h1Second: "Car Suits",
    subtitle: "USAC, World of Outlaws, ASCS-compliant custom sprint car racing suits. SFI 3.2A/5 multi-layer Nomex®, arm-restraint compatible, dust-seal collar, methanol-spec protection. From $329.",
    primaryCtaHref: "/custom-race-suit/order",
    primaryCtaText: "Design Your Sprint Suit",
    certBadge: "SFI 3.2A/5",
    builtForIntro: "Sprint car racing has a unique risk profile that most off-the-shelf suits weren't built around. Our custom sprint car racing suits address all four:",
    builtForPoints: [
      { title: "Arm-restraint compatible shoulder construction", detail: "Sprint cars require arm restraints. The suit's shoulder construction has to clear the restraint anchor without bunching." },
      { title: "Dust-seal collar and cuffs", detail: "Dirt sprint cars throw enough clay into the cockpit to coat the inside of an open-collar suit. Our suits use higher collars, elastic cuffs, and storm flaps." },
      { title: "SFI 3.2A/5 multi-layer Nomex®", detail: "Methanol burns nearly invisible. Multi-layer Nomex® gives you 7–10 seconds of protection vs 3 seconds for single-layer 3.2A/1." },
      { title: "Reinforced shoulder and knee abrasion panels", detail: "Sprint flips are violent. Reinforced panels keep the Nomex® intact through the slide." },
    ],
    sanctioningIntro: "Every major US sprint car sanctioning body specifies SFI 3.2A/5 as the floor. Built to 2026 rulebook specifications:",
    sanctioningBodies: [
      { name: "USAC (Silver Crown, Sprint, Midget)", requirement: "SFI 3.2A/5 minimum across all divisions. Arm restraints SFI 3.3 mandatory." },
      { name: "World of Outlaws Sprint Cars", requirement: "SFI 3.2A/5 minimum. Fire-resistant underwear strongly recommended." },
      { name: "ASCS Sprint Cars (360 and 410)", requirement: "SFI 3.2A/5 minimum." },
      { name: "POWRi (Sprint, Midget, Outlaw Micro)", requirement: "SFI 3.2A/5 minimum across all divisions." },
      { name: "Weekly / hobby class winged sprint", requirement: "Most weekly tracks specify SFI 3.2A/5 for any winged sprint. Some accept SFI 3.2A/1 for hobby/non-wing classes." },
    ],
    sanctioningCallout: "If you race across multiple sanctioning bodies in a season, build to the strictest one — usually USAC. Our custom sprint car suits ship USAC-spec by default unless you tell us otherwise.",
    relatedReading: [
      { href: "/blog/best-sprint-car-racing-suit", title: "Best Sprint Car Racing Suit — USAC, World of Outlaws & ASCS Rules", note: "Definitive guide" },
      { href: "/blog/sfi-rated-racing-suit-by-class", title: "SFI Rated Racing Suit by Class", note: "Discipline-by-discipline rating breakdown" },
      { href: "/blog/perfect-custom-fit-racing-suit", title: "Custom Fit Tips", note: "Sprint car cockpit fit is unforgiving — measure right" },
    ],
    ctaTitle: "Ready for the Knoxville Nationals?",
    ctaSubtitle: "Custom sprint car racing suits with arm-restraint-compatible shoulder construction, dust-seal collar, methanol-spec multi-layer Nomex®. USAC, World of Outlaws, ASCS, POWRi compliant. Order by early summer to be Nationals-ready.",
  },

  "dirt-late-model": {
    slug: "custom-dirt-late-model-suit",
    breadcrumb: "Custom Dirt Late Model Suit",
    disciplineTag: "Dirt Late Model",
    disciplineFullName: "Dirt Late Model Racing",
    suitNoun: "dirt late model suits",
    h1First: "Custom Dirt",
    h1Second: "Late Model Suits",
    subtitle: "Lucas Oil, World of Outlaws, and weekly-track dirt late model custom racing suits. SFI 3.2A/5 multi-layer with abrasion-resistant panels, dust seal at collar and cuffs, and reinforced shoulder construction. From $329.",
    primaryCtaHref: "/custom-race-suit/order",
    primaryCtaText: "Design Your Dirt Suit",
    certBadge: "SFI 3.2A/5",
    builtForIntro: "Dirt late model racing puts a suit through more abrasion and dust exposure than almost any other oval-track discipline. Our dirt late model suits are spec'd around four priorities:",
    builtForPoints: [
      { title: "SFI 3.2A/5 multi-layer Nomex® baseline", detail: "Standard floor for Lucas Oil, World of Outlaws Late Models, and most regional touring." },
      { title: "Aggressive dust seal at collar and cuffs", detail: "Higher collar, elastic wrist and ankle cuffs, storm flap over zipper — seals out clay and dust from 30-lap features." },
      { title: "Reinforced shoulder, knee, and seat abrasion panels", detail: "Cordura or Kevlar reinforcement at the contact zones for slides and tire-barrier impacts." },
      { title: "Darker exterior color options", detail: "Black, deep navy, and dark red mask dirt accumulation between heat races. Your team graphics still pop." },
    ],
    sanctioningIntro: "Dirt late model sanctioning bodies share a common SFI 3.2A/5 floor with discipline-specific extras:",
    sanctioningBodies: [
      { name: "Lucas Oil Late Model Dirt Series", requirement: "SFI 3.2A/5 minimum. Fire-resistant underwear strongly recommended." },
      { name: "World of Outlaws Late Models", requirement: "SFI 3.2A/5 minimum across the touring series." },
      { name: "DIRTcar / Northeast Late Models", requirement: "SFI 3.2A/5 minimum. Check track-specific bulletins for higher requirements at premier events." },
      { name: "Weekly track late model classes", requirement: "Most weekly tracks specify SFI 3.2A/5; some accept SFI 3.2A/1 for hobby-stock variants." },
      { name: "IMCA-style modified late model", requirement: "SFI 3.2A/5 minimum." },
    ],
    sanctioningCallout: "Dirt late model is one of the few classes where over-spec'd protection (3.2A/10) makes sense for upper-tier touring drivers — methanol fuel loads + closed-cockpit heat make extra TPP worth the weight.",
    relatedReading: [
      { href: "/blog/sfi-rated-racing-suit-by-class", title: "SFI Rated Racing Suit by Class", note: "Full discipline-by-discipline rating guide" },
      { href: "/blog/tpp-rating-explained", title: "TPP Rating Explained", note: "Why TPP matters more than SFI tier alone" },
      { href: "/blog/aftermarket-racing-suits", title: "When to Upgrade From Stock Gear", note: "Especially relevant for dirt — abrasion ages suits fast" },
    ],
    ctaTitle: "Custom Dirt Late Model Racing Suits — Built for the Saturday Night Grind",
    ctaSubtitle: "SFI 3.2A/5 multi-layer construction, dust-seal collar, reinforced abrasion panels at shoulders and seat. Lucas Oil, World of Outlaws, weekly track compliant. Starting at $329 with free shipping.",
  },

  "road-racing": {
    slug: "custom-road-racing-suit",
    breadcrumb: "Custom Road Racing Suit",
    disciplineTag: "Road Racing",
    disciplineFullName: "Road Course / Club Racing",
    suitNoun: "road racing suits",
    h1First: "Custom Road",
    h1Second: "Racing Suits",
    subtitle: "SCCA, NASA, and vintage road racing custom racing suits. SFI 3.2A/5 multi-layer Nomex® or FIA 8856-2018 equivalents for international series. From $329.",
    primaryCtaHref: "/custom-race-suit/order",
    primaryCtaText: "Design Your Road Suit",
    certBadge: "SFI 3.2A/5",
    builtForIntro: "Road racing covers a wide spectrum from amateur club racing to professional endurance. Our road racing suits are built to span the major US series:",
    builtForPoints: [
      { title: "SFI 3.2A/5 or FIA 8856-2018", detail: "Both standards available. SFI for SCCA, NASA, Trans Am amateur. FIA 8856-2018 for IMSA professional classes and international series." },
      { title: "Stretch panels for road-course range of motion", detail: "Road racing demands more shoulder, elbow, and hip mobility than oval. Stretch knit at the underarms, sides, and inner elbows." },
      { title: "Moisture-wicking inner liner", detail: "30-minute SCCA races + 45-minute NASA enduros + 2-hour Trans Am races demand a moisture-wicking liner. Standard on all our road racing suits." },
      { title: "Compatible with cool-shirt and head-cooling systems", detail: "Pre-installed grommets for cool-shirt tubes, designed not to block the airflow." },
    ],
    sanctioningIntro: "Road racing has clear SFI/FIA equivalencies across the major US series:",
    sanctioningBodies: [
      { name: "SCCA Club Racing", requirement: "SFI 3.2A/5 minimum for most classes. FIA 8856-2018 accepted as equivalent." },
      { name: "NASA Road Racing", requirement: "SFI 3.2A/5 minimum across HPDE 4 and competition classes." },
      { name: "Trans Am (TA, TA2)", requirement: "SFI 3.2A/5 minimum; pro classes increasingly require FIA 8856-2018." },
      { name: "IMSA Michelin Pilot Challenge", requirement: "FIA 8856-2018 required by class rules." },
      { name: "Vintage racing (HSR, SVRA, VARA)", requirement: "SFI 3.2A/5 minimum across vintage clubs. Period-correct exemptions exist for the car but not the driver." },
    ],
    sanctioningCallout: "For amateur road racers, SFI 3.2A/5 is sufficient for 95% of US series. FIA 8856-2018 is mandatory only for IMSA professional and a few international championships — don't overspend on FIA if SFI does the job.",
    relatedReading: [
      { href: "/blog/sfi-rated-racing-suit-by-class", title: "SFI Rated Racing Suit by Class", note: "Including road racing requirements" },
      { href: "/blog/endurance-racing-suit-guide", title: "Endurance Racing Suits Explained", note: "FIA vs SFI deep dive" },
      { href: "/blog/perfect-custom-fit-racing-suit", title: "Custom Fit Tips", note: "Road-course cockpits demand more shoulder mobility" },
    ],
    ctaTitle: "Custom Road Racing Suits — SCCA, NASA, and Beyond",
    ctaSubtitle: "SFI 3.2A/5 or FIA 8856-2018 — your choice. Stretch panels for road-course range of motion, moisture-wicking inner liner for long sessions, cool-shirt compatible. From $329.",
  },

  "junior-karting": {
    slug: "custom-junior-karting-suit",
    breadcrumb: "Custom Junior Karting Suit",
    disciplineTag: "Junior Karting",
    disciplineFullName: "Junior / Cadet Karting",
    suitNoun: "junior karting suits",
    h1First: "Custom Junior",
    h1Second: "Karting Suits",
    subtitle: "CIK Level 2 custom karting suits for cadet, micro, mini, and junior karting drivers ages 8–15. WKA, SKUSA, Rotax Max, IAME compliant. Sublimated graphics with growth-room construction. From $329.",
    primaryCtaHref: "/custom-karting-suit/order",
    primaryCtaText: "Design Your Junior Suit",
    certBadge: "CIK Level 2",
    builtForIntro: "Junior karting has its own design priorities — kids grow, weekends are long, and dust/dirt accumulates fast. Our junior karting suits are built around four:",
    builtForPoints: [
      { title: "CIK Level 2 with SFI 3.2A/1 baseline", detail: "WKA, SKUSA, Rotax Max Challenge USA, IAME USA, and USPKS all specify CIK Level 2. Required at every national-level event." },
      { title: "Built-in stretch panels at the knees", detail: "Kids grow. Knee stretch panels add a season of useful life before the suit needs replacement." },
      { title: "Adjustable Velcro cuffs at wrist and ankle", detail: "Cuffs let the suit grow with the driver instead of binding within a season." },
      { title: "Dirt-tolerant color choices", detail: "Brand red, deep blue, black — looks pristine on day one, looks battle-tested for the right reasons by Saturday afternoon." },
    ],
    sanctioningIntro: "Every major US junior karting sanctioning body specifies CIK Level 2 as the baseline:",
    sanctioningBodies: [
      { name: "WKA (Cadet, Junior classes)", requirement: "CIK Level 2 minimum for all national-level events." },
      { name: "SKUSA (Micro Swift, Mini Swift, Junior)", requirement: "CIK Level 2 for all sanctioned events. SuperNationals adds extra equipment requirements for KZ class." },
      { name: "Rotax Max Challenge USA (Junior, Mini Max)", requirement: "CIK Level 2 with fit-check at registration for junior classes." },
      { name: "IAME USA East / West (Mini Swift, Junior Swift)", requirement: "CIK Level 2; tech inspectors strict about suit condition." },
      { name: "USPKS / regional series", requirement: "CIK Level 2 minimum across the board." },
    ],
    sanctioningCallout: "Parent tip: order the size that fits today's chest and shoulders correctly. Length adjusts via cuffs and stretch panels — chest and shoulders don't. Most juniors get 1 to 1.5 seasons out of a properly-fit suit.",
    relatedReading: [
      { href: "/blog/karting-suit-sizing-guide", title: "Karting Suit Sizing Guide", note: "Junior, cadet, senior, shifter fit" },
      { href: "/blog/sfi-rated-racing-suit-by-class", title: "SFI Rated Racing Suit by Class", note: "Karting section" },
    ],
    ctaTitle: "Custom Junior Karting Suits — Built to Last a Full Season",
    ctaSubtitle: "CIK Level 2 certified, sublimated graphics, stretch panels at the knees, adjustable Velcro cuffs. WKA, SKUSA, Rotax Max, IAME compliant. Starting at $329.",
  },

  "shifter-kart": {
    slug: "custom-shifter-kart-suit",
    breadcrumb: "Custom Shifter Kart Suit",
    disciplineTag: "Shifter Karting",
    disciplineFullName: "Shifter Karting (KZ, IAME X30 Shifter)",
    suitNoun: "shifter kart suits",
    h1First: "Custom Shifter",
    h1Second: "Kart Suits",
    subtitle: "CIK Level 2 custom shifter kart suits for KZ, IAME X30 Shifter, and Stock Honda Moto Shifter racers. Reinforced right-shoulder, moisture-wicking liner, paddle-shift inner elbow stretch panels. From $329.",
    primaryCtaHref: "/custom-karting-suit/order",
    primaryCtaText: "Design Your Shifter Suit",
    certBadge: "CIK Level 2",
    builtForIntro: "Shifter karting is the karting discipline that demands the most from a suit — longer sessions, hotter engines, constant paddle-shift work. Our shifter kart suits are spec'd around four upgrades:",
    builtForPoints: [
      { title: "Reinforced right-shoulder abrasion panel", detail: "Shifter driving puts the right shoulder under sustained load against the seat. Reinforcement extends useful life by a full season." },
      { title: "Cooler moisture-wicking inner liner", detail: "Shifter sessions run longer than sprint karting. Engine sits closer to the driver. Mesh inner liner drops core body temp meaningfully." },
      { title: "Stretch panel at the inner elbow", detail: "Constant paddle-shift motion fatigues the right inner elbow first. Stretch panel relieves binding over a long heat race." },
      { title: "Reinforced collar with breathable mesh", detail: "Shifter drivers wear neck restraints or high-collar helmets. Collar has to clear without choking." },
    ],
    sanctioningIntro: "Shifter karting has CIK Level 2 baseline plus discipline-specific extras at the top tier:",
    sanctioningBodies: [
      { name: "SKUSA Pro Shifter / KZ", requirement: "CIK Level 2 minimum. SuperNationals KZ class requires additional SFI 3.2A/1 abrasion certification." },
      { name: "WKA Pro Shifter", requirement: "CIK Level 2 across the national series." },
      { name: "USPKS / regional shifter classes", requirement: "CIK Level 2; some series may require specific abrasion patches." },
      { name: "IAME X30 Shifter", requirement: "CIK Level 2 across the IAME USA East and West regions." },
      { name: "Stock Honda Moto Shifter", requirement: "CIK Level 2 minimum." },
    ],
    sanctioningCallout: "If you're stepping up from non-shifter to shifter, the suit is one of the upgrades that pays back fastest. Same fire rating, but the construction differences (reinforced shoulder, cooler liner, paddle-shift stretch) matter for the longer sessions and harder physical work.",
    relatedReading: [
      { href: "/blog/karting-suit-sizing-guide", title: "Karting Suit Sizing Guide", note: "Shifter-specific section" },
      { href: "/blog/sfi-rated-racing-suit-by-class", title: "SFI Rated Racing Suit by Class", note: "Karting section" },
    ],
    ctaTitle: "Custom Shifter Kart Suits — Built for the Long Session",
    ctaSubtitle: "CIK Level 2 with reinforced right-shoulder, moisture-wicking liner, paddle-shift inner elbow stretch. SKUSA, WKA, IAME, USPKS compliant. Starting at $329.",
  },
};
